import { ApiProperty } from '@nestjs/swagger';
import { Base } from '@syncslot/shared';
import { Column, Entity, ManyToOne, JoinColumn } from 'typeorm';
import { ContactEntity } from './contact.entity';

export enum MessageStatus {
  PENDING = 'PENDING',
  SENT = 'SENT',
  FAILED = 'FAILED',
}

@Entity('message_history')
export class MessageHistoryEntity extends Base {
  @Column('text', {
    name: 'prompt',
    comment: 'Original instruction from user',
  })
  @ApiProperty({ example: 'Dile que nos vemos mañana a las 5' })
  prompt: string;

  @Column('text', {
    name: 'generated_message',
    nullable: true,
    comment: 'Message generated by IA',
  })
  @ApiProperty({ example: 'Estimado, confirmando nuestra reunión de mañana a las 17:00. Saludos.' })
  generatedMessage: string | null;

  @Column('enum', {
    name: 'status',
    enum: MessageStatus,
    default: MessageStatus.PENDING,
    comment: 'Status of the dispatch',
  })
  @ApiProperty({ example: MessageStatus.SENT, enum: MessageStatus })
  status: MessageStatus;

  @Column('text', {
    name: 'error_reason',
    nullable: true,
    comment: 'Reason if failed',
  })
  @ApiProperty({ example: 'WhatsApp no está conectado' })
  errorReason: string | null;

  @ManyToOne(() => ContactEntity)
  @JoinColumn({ name: 'contact_id' })
  contact: ContactEntity;
}
